[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    knolleary/PubSubClient@^2.8       ; MQTT Client library
    bblanchon/ArduinoJson@^6.21.3    ; Stack-safe JSON serialization

build_flags = 
    -D CORE_DEBUG_LEVEL=5

upload_port = COM4
monitor_port = COM4
upload_speed = 115200   

